mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'))
]

mysite/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
# <xyz> <--- to capture a value from url, angle brackets are used( here int)
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailsView.as_view(), name = 'details'),
    path('<int:pk>/results/',views.ResultsView.as_view(), name = 'results'),
    path('<int:question_id>/votes_count/',views.votes_count, name = 'votes_count')
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# question_text is field of the model which is used as column in database
# models tells the whereabouts of our data in a app.
class Question(models.Model):
    question_text = models. CharField(max_length=250 )
    published_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
# time handling in python
        return now -datetime.timedelta(days=1) <= self.published_date <= now

# since there can be more than one choice for question, we will use "foreign key" - creates many to one relationship 
# use of on_delete = models.cascade --> if the question is deleted, the choices will be deleted automatically
class options(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    option_text1 = models.CharField(max_length=250,default = '')
    votes_count = models.IntegerField(default = 0)
    def __str__(self):
        return self.option_text1

mysite/polls/views.py
# Sort of front end is written here
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question,options

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:5]

class DetailsView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'

    def get_queryset(self):
        return Question.objects.filter(published_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def votes_count(request,question_id):
    question = get_object_or_404(Question,pk = question_id)
    context = {
        'question': question,
        'error_message': "You didn't select a choice."
    }
    try:
        selected_option = question.options_set.get(pk=request.POST['options'])
    except(KeyError,options.DoesNotExist):
# Redisplaying the question voting form
        return render(request, 'polls/details.html', context )
    else:
        selected_option.votes_count += 1
        selected_option.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/details.html
<h1>
    {{question.question_text}}
</h1>
{% if error_message %}
<p>
    <strong>{{ error_message  }}</strong>
</p>
{% endif %}

<form action= "{% url 'polls:votes_count' question.id %}" method = "POST" >
{# csrf_token in used to prevent csrf attack #}
{% csrf_token %}
{% for options in question.options_set.all %}
    <input type = "radio" name = "options" id = "options{{forloop.counter}}" value="{{options.id}}">
    <label for = "choice{{ forloop.counter }}" >{{ options.option_text1 }}</label>

<br>
<br>
{% endfor %}
<input type = "submit" value = "vote">

</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}

</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1> {{question.question_text}}</h1>
<ul>
    {% for options in question.options_set.all %}
    <li>
        {{ options.option_text1}} --> {{options.votes_count}} votes_count{{options.votes_count|pluralize}}
    </li>
    {% endfor %}
</ul>
<a href = "{% url 'polls:details' question.id %}"> Vote again ?</a>